name: Check if Zhihu.com has closed down

on:
  schedule:
    - cron: "*/30 * * * *"
  push:
    branches:
      - master

jobs:
  checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn --frozen-lockfile --non-interactive
      - name: Run Script
        run: |
          node index.js
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          GH_USERNAME: yiruka114514
          GIST_ID: "9972c01ad3be9001435a6cb7f9c62e21"
